### ISSUE TITLE
Support for minification when in typescript mode

### ISSUE THREAD

**Issue by hackerrdave** [selsamman/supertype#19]
The `getName()` function when assigning `__name__` doesn't work quite right when using minified code. Currently the regex it uses is this:

```javascript
            function getName () {
                return target.toString().match(new RegExp(/.*function *(.*)\(/))[1];
            }
```

would like to have it updated to:

```javascript
            function getName () {
                return target.toString().match(/function ([^(]*)/)[1];
            }
```

**Comment by CSMastermind** [comment]
I'll make the change for now but I'm leaving this issue open because we should revisit if a regex is the right way to extract this information.
